### ISSUE TITLE
 Ask code related questions

### ISSUE THREAD

**Issue by LKAMING97** [DoctorKey/LSHFM.multiclassification#1]
Hello, first of all praise this is a very good job, author, I would like to know what is the actual function of this part of the code, can you help me explain it? THANKS!!!

![image](https://user-images.githubusercontent.com/90093699/194693773-9cf13e80-f2aa-4567-95ed-62bbbc246f91.png)

**Comment by DoctorKey** [comment]
Thank you for pointing out this problem. I think these codes are useless. I have removed them.

**Comment by LKAMING97** [comment]
Hello, I would like to know in the multi-label task, how to confirm that the feature space of the student model and the teacher model in the first step is aligned, because I debug the code of the first step and found that in the training process of aligning the feature space, only training , without verification,  how to judge whether it is aligned
